### ISSUE TITLE
角色权限管理、资源管理

### ISSUE THREAD

**Issue by rainbow702** [Caratacus/Crown#5]
登录了试用环境，试用了一下，感觉还不错。

这个试用项目，包含了通用的 用户-角色-资源 管理模块了，如果能添加  用户-角色 之间的管理功能，以及，角色-资源 之间的管理功能，就更加完美了。

不知道作者是否有这方面的打算。

**Comment by Caratacus** [comment]
[https://github.com/Caratacus/Crown2](https://github.com/Caratacus/Crown2)
